language: cpp

addons:
  apt:
    packages:
      - cmake

compiler:
  - clang
  - gcc

before_install:
  - bash prepare.sh

script:
  - mkdir build && cd build || exit
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make
